load('10-100_data','basic_pyle_f','basic_pyle_m','dual_full_lt_pyle_f','dual_full_lt_pyle_f','dual_full_lt_pyle_f','open_loop_pyle_m')
figure;
semilogx(basic_pyle_f,basic_pyle_m);
ax = gca;
title('Basic Pyle PLPW6D Response');
xlabel('Frequency / Hz');
ylabel('Magnitude / dB');
figure;
semilogx(dual_full_lt_pyle_f,dual_full_lt_pyle_m);
ax = gca;
title('Low-frequency enchanced Pyle PLPW6D Response');
xlabel('Frequency / Hz');
ylabel('Magnitude / dB');
figure;
semilogx(open_loop_pyle_f,open_loop_pyle_m);
ax = gca;
title('Fully open-loop compensated Pyle PLPW6D');
xlabel('Frequency / Hz');
ylabel('Magnitude / dB');
figure;
ax = gca;
semilogx(basic_pyle_f,basic_pyle_m,'r');
title('Comparing Pyle PLPW6D Responses');
xlabel('Frequency / Hz');
ylabel('Magnitude / dB');
ylim([-18 2]);
hold on;
semilogx(dual_full_lt_pyle_f,dual_full_lt_pyle_m,'b');
ylim([-18 2]);
hold on;
semilogx(open_loop_pyle_f,open_loop_pyle_m,'g');
ylim([-18 2]);
legend('Basic response','Bass-boosted response','Fully corrected response')